### ISSUE TITLE
Gear and Accessories are not compiling

### ISSUE THREAD

**Issue by qfoxb** [LockpickInteractive/Rbx2Source#17]
![image](https://user-images.githubusercontent.com/42038239/218467693-2a6dd85d-0e19-403b-8f20-bd0f140539f0.png)
**Compiling Hats and gear is currently broken.**

**Comment by qfoxb** [comment]
Doing more research and testing in the development branch

**Comment by qfoxb** [comment]
Unable to get anything relating to gears or hats now, gonna keep working on it

**Comment by qfoxb** [comment]
This appears to be API related, not sure what's causing it

**Comment by qfoxb** [comment]
99% sure this is api related, see Line 165 of Web/Asset.cs

**Comment by idkthegithub** [comment]
so which api is now used?

**Comment by qfoxb** [comment]
Accessories now compile correctly on the development branch. This issue will be closed when the development branch is merged.

**Comment by idkthegithub** [comment]
how bout avatars? do they compile properley, or they still need fixes?

**Comment by superluckyaki** [comment]
public void Assemble(UserAvatar avatar)
{
    if (avatar == null)
    {
        throw new ArgumentNullException(nameof(avatar));
    }

    // Check if other objects that are being used in the method are null and handle accordingly

    // Assemble the avatar
    // ...
}

**Comment by qfoxb** [comment]
Fixed by version 2.71!
