### ISSUE TITLE
Avatar asssembling not working

### ISSUE THREAD

**Issue by robloxkid03** [LockpickInteractive/Rbx2Source#18]
![Rbx2Source v2 62 3_12_2023 4_13_42 PM](https://user-images.githubusercontent.com/127700303/224580692-cb9cf320-15a9-4144-91c5-28ce390f4dcf.png)
I got a problem porting ROBLOX avatars to Garry's Mod. Can you fix it?

**Comment by qfoxb** [comment]
Are you using layered clothing? Plus this is not my build or is a very old build, would have my twitter username in it
Please download the latest release

**Comment by qfoxb** [comment]
Closing as invalid, will reopen if issue can be replicated on latest release

**Comment by qfoxb** [comment]
I can replicate this on my build. Will do further investigation

**Comment by qfoxb** [comment]
API related again. API.roblox.com is now dead and along with it, the Users/Get-By-Username?username= method is now dead. The replacement is a post request, WTF. I'll keep trying

**Comment by idkthegithub** [comment]
i think you should make it so you put your user id so it goes like: https://www.roblox.com/users/(userid)

**Comment by qfoxb** [comment]
You mean put user ID instead of username? I would do that only as a last resort if I can't get usernames to work.

**Comment by idkthegithub** [comment]
i meant that, yeah.

**Comment by qfoxb** [comment]
Alright, i'm gonna need some help because at the moment it's REALLY confusing. If anyone knows how to help please open a pull request

**Comment by qfoxb** [comment]
What we know
- There was an endpoint on api.roblox.com that used to be GET and is now POST on users.roblox.com
- The returned JSON is different and the code needs to be adapted to work properly

**Comment by qfoxb** [comment]
Line 93 of Web/UserData.cs starts the FromUsername function that needs to be  updated

**Comment by idkthegithub** [comment]
is the json heavily edited or?

**Comment by idkthegithub** [comment]
could u try using chatgpt

**Comment by qfoxb** [comment]
Been trying to get it to give me the right code but it always has issues or outright doesn't work

**Comment by Verusmp4** [comment]
> Again, Still need to work on this. I will get to it eventually

Are you still working on it?

**Comment by qfoxb** [comment]
> > Again, Still need to work on this. I will get to it eventually
> 
> Are you still working on it?

As i said, i will get to it. I don't have any time to work on anything right now due to school. If you would like to contribute feel free to open a pull request

**Comment by qfoxb** [comment]
> The only model I can compile is this Model ID for gear and accesories: 44113968

This is a different issue. Please go to #17 to talk about accessories and gear

**Comment by qfoxb** [comment]
I am going to lock this thread for now.

**Comment by qfoxb** [comment]
This issue actually seems really, really complicated. It will require reformatting a lot of the code to accept the new format provided by Roblox. If anyone is more knowledgeable, or knows someone who is more knowledgeable, please reply here or have them reply here.

**Comment by qfoxb** [comment]
Fixed by version 2.71!
