### ISSUE TITLE
Doesn't work... like, at all.

### ISSUE THREAD

**Issue by TheTarr2** [LockpickInteractive/Rbx2Source#21]
**Describe the bug**
When opened, it says "An error occurred while trying to fetch the user! Either the user does not exist, is banned, or something went wrong with the request." It also says this whenever I put anyone in, except for the starter character, then it says the object is not set to an instance of an object.

**To Reproduce**
1. The starting bug
1a. open the software
1b. error message pops up

2. The other bug
2a. keep it open, put someone's roblox username in
2b. error message pops up, same one from bug 1

**Expected behavior**
Exports the character/gear to SFM, or GMOD, or whatever it's used for.

**Screenshots**
![image](https://user-images.githubusercontent.com/130080387/230498508-b77029ee-62a6-4e98-85b4-c3091ade8d65.png)
![image](https://user-images.githubusercontent.com/130080387/230498510-17176947-dac9-4b19-9869-0b5ad260cde1.png)

**Desktop**
 - OS: Windows 11, 64-bit
 - Version 22H2

I know you're not the original creator, but do you know how to fix this problem? Does this happen on another OS?

**Comment by TheTarr2** [comment]
I just checked, this is the same issue brought up by thebrokendoggo. Since you said it's an ongoing issue, I guess I'll just wait until you can fix it. Good luck, I don't understand a lick of this stuff and I'm hoping you can figure out how to fix this issue.

**Comment by qfoxb** [comment]
Closing as duplicate! thanks for checking
