### ISSUE TITLE
Unhandled exception has occurred in your application

### ISSUE THREAD

**Issue by KurtMGITHUB** [LockpickInteractive/Rbx2Source#25]
**Describe the bug**
Whenever I open the application it errors and says "Object reference not set to an instance of an object." and even if I continue and ignore it would start to appear again if I try to use the application and compile.

**To Reproduce**
1. Go to 'Rbx2Source-main'
2. Click on 'Rbx2source.exe'
3. See error

**Expected behavior**
The error would not appear and I could use the app normally like the others

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11 x64]
 - Version [10.0.22621 Build 22621]

**Comment by timelessnesses** [comment]
this due to roblox removed old legacy API (api.roblox.com/users and api.roblox.com/get-by-username) so it actually failed to fetch user information (that's currently set by default in the program) and it will also fail every time you try to compile any avatars (idk about gears)
