### ISSUE TITLE
system.nullreferenceexception: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by marksilver0110** [LockpickInteractive/Rbx2Source#28]
![스크린샷 2023-04-19 081516](https://user-images.githubusercontent.com/131215362/232936724-d78dd1ea-9c8e-4fa1-a66c-1b782c234cc1.png)

I am a Korean who uses this program. However, at some point, the phrase " system.nullreferenceexception: Object reference not set to an instance of an object " appears on the screen and the model port is not being made
Please give me a solution to this error or fix the problem!

**Comment by qfoxb** [comment]
When does this happen? What was the User/Accessory ID you were compiling for?

**Comment by marksilver0110** [comment]
> 언제 이런 일이 발생합니까? 컴파일하려는 사용자/액세서리 ID는 무엇입니까?

It always occurs when starting the program and porting accessories and avatars.

**Comment by timelessnesses** [comment]
that seems like old version to be honest since this version is tested by me and qfoxb.   
i suggest you should download dotnet runtime 4.7 or 4.8 and try running it again

**Comment by timelessnesses** [comment]
thanks for response!  
there's opening issue (#27) and a fix (#29)

**Comment by qfoxb** [comment]
Ok i'm closing this issue in favor of #27 but restarting the program seems to fix the object reference not set to an instance of an object bug
