### ISSUE TITLE
Would you like to merge this into Rbx2Source?

### ISSUE THREAD

**Issue by MaximumADHD** [LockpickInteractive/Rbx2Source#35]
I'm not against keeping the project alive, I just didn't have the time or resources available to deal with the upkeep nightmare on my own. I've unarchived the repository if you're interested in making a merge pull-request.

**Comment by qfoxb** [comment]
Hell yeah, i'd love that. Would I be able to keep the credits page contributors i added who helped me maintain it? I'll open a PR right now

**Comment by qfoxb** [comment]
Opened PR https://github.com/MaximumADHD/Rbx2Source/pull/89

**Comment by MaximumADHD** [comment]
Yeah that's cool.
