### ISSUE TITLE
Does not launch

### ISSUE THREAD

**Issue by Showey231** [LockpickInteractive/Rbx2Source#7]
No matter what i do, move the game to C: drive, move it back, reinstall, change config, launch from administrator. It does not detect my gmod.

**Comment by qfoxb** [comment]
Are you sure you're puttiing the correct directory? Look under `C:\Program Files (x86)\Steam\steamapps\common`, is garry's mod listed? If it's there, don't use a config file. If it isn't, find the steamapps folder and set the config file to the folder that steamapps is in.

**Comment by qfoxb** [comment]
> > I'm going to be putting tutorials up soon, so it should be a lot easier to set up.
> 
> yeah, that will be nice
Did my fix work?

**Comment by qfoxb** [comment]
Hey, i'm going to be putting the tutorials up in the next day or two over at the offical [StarLand Youtube channel](https://www.youtube.com/channel/UCQ1bC8606j5SSGJdJzSq_9A/). There isn't anything yet as they're still all being edited and rendered.

**Comment by qfoxb** [comment]
The main tutorial is up on the channel at [https://www.youtube.com/watch?v=5Z3vgvG_Uq8](https://www.youtube.com/watch?v=5Z3vgvG_Uq8)

**Comment by qfoxb** [comment]
I'm gonna close this issue for now, if you comment on it or this thread gets more traction i'll reopen it

**Comment by qfoxb** [comment]
You should try with the latest update, it no longer requires a config file and will automatically find the games.
